//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMergeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_links
    {
        public decimal link_id { get; set; }
        public string link_url { get; set; }
        public string link_name { get; set; }
        public string link_image { get; set; }
        public string link_target { get; set; }
        public string link_description { get; set; }
        public string link_visible { get; set; }
        public decimal link_owner { get; set; }
        public int link_rating { get; set; }
        public System.DateTime link_updated { get; set; }
        public string link_rel { get; set; }
        public string link_notes { get; set; }
        public string link_rss { get; set; }
    }
}
