//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMergeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_term_taxonomy
    {
        public decimal term_taxonomy_id { get; set; }
        public decimal term_id { get; set; }
        public string taxonomy { get; set; }
        public string description { get; set; }
        public decimal parent { get; set; }
        public long count { get; set; }
    }
}
