//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_ewwwio_images
    {
        public int id { get; set; }
        public string path { get; set; }
        public string image_md5 { get; set; }
        public string results { get; set; }
        public string gallery { get; set; }
        public Nullable<long> image_size { get; set; }
        public Nullable<long> orig_size { get; set; }
    }
}
