// <auto-generated />
namespace Uspelite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class videosarticles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(videosarticles));
        
        string IMigrationMetadata.Id
        {
            get { return "201603101306191_videos-articles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
